version: '3.8'

services:
  app:
    image: wjd4204/github-actions-iamsouf:latest
    ports:
      - "8080:8080"
    env_file:
      - ./souf.env
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - redis
      - rabbitmq

  redis:
    image: redis:7.2.4
    container_name: redis-container
    ports:
      - "6379:6379"
    command: redis-server --bind 0.0.0.0
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Web Management
      - "61613:61613"   # STOMP
#    env_file:
#      - ./souf.env
#    environment:
#      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
#      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always
    command: >
      bash -c "rabbitmq-plugins enable --offline rabbitmq_stomp &&
               rabbitmq-plugins enable --offline rabbitmq_management &&
               rabbitmq-server"

volumes:
  rabbitmq_data: