version: '3.8'

services:
  app:
    image: wjd4204/github-actions-iamsouf:latest
    ports:
      - "8080:8080"
    env_file:
      - ./iamsouf.env
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"