spring:
  profiles:
    active: ${SPRING_PROFILE:dev}

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cache:
    type: redis

  application:
    name: soufwebsite

  mail:
    host: smtp.zoho.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: "/"

jwt:
  secret: ${JWT_SECRET}
  access:
    expiration: 1800000
    header: Authorization
  refresh:
    expiration: 3600000
    header: RefreshToken

cloud:
  aws:
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: ${BUCKET_NAME}
    ecs:
      cluster: ${ECS_CLUSTER}
      task-definition: ${ECS_TASK_DEFINITION}
      subnet: ${ECS_SUBNET}
      security-group: ${SECURITY_GROUP}
    sqs:
      enabled: true

websocket:
  relay:
    host: rabbitmq
    port: 61613
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

opensearch:
  host: ${OPENSEARCH_HOST}
  username: ${OPENSEARCH_USERNAME}
  password: ${OPENSEARCH_PASSWORD}

  index:
    name: souf-website-index