spring:
  datasource:
    url: jdbc:postgresql://${TEST_DB_URL}/souf_testdb
    username: ${TEST_DB_USERNAME}
    password: ${TEST_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update