spring:
  datasource:
    url: jdbc:postgresql://${DB_URL}/souf
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate