spring:
  datasource:
    url: jdbc:postgresql://${DB_URL}/souf
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      port: ${REDIS_PORT:6379}
      host: ${REDIS_HOST:redis-container}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: false

  jpa:
    hibernate:
      ddl-auto: update

  logging:
    level:
      org:
        hibernate:
          SQL: debug
        springframework:
          jdbc:
            core:
              JdbcTemplate: DEBUG
              PreparedStatementCreator: OFF
              JdbcTemplate$SimplePreparedStatementCreator: OFF

slack:
  token: ${SLACK_TOKEN}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false