name: test-CI-CD

# 워크플로우가 실행될 조건을 정의합니다.
on:
  push:
    branches: [ "dev" ] # dev 브랜치에 push가 발생하면 실행됩니다.

# 워크플로우가 접근할 수 있는 권한을 설정합니다.
permissions:
  contents: read

jobs:
  # Docker 이미지를 빌드하고 Docker Hub에 푸시하는 작업을 정의합니다.
  build-docker-image:
    runs-on: ubuntu-latest # 워크플로우가 실행될 환경을 지정합니다.
    steps:
      # 리포지토리의 코드를 체크아웃합니다.
      - uses: actions/checkout@v3

      - name: Free disk space
        run: |
          docker system prune -af --volumes

      # JDK 17을 설치하고 환경을 설정합니다.
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Gradle Wrapper 파일에 실행 권한을 부여합니다.
      - name: Grant Execute Permission For Gradlew
        run: chmod +x gradlew

      # gradle caching - 빌드 시간 향상
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Gradle을 사용하여 프로젝트를 빌드합니다.
      - name: Build With Gradle
        run: ./gradlew build -x test

#      # 디렉토리 생성
#      - name: Create deploy directory
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.EC2_HOST }}
#          username: ec2-user
#          key: ${{ secrets.EC2_SSH_KEY }}
#          script: |
#            mkdir -p /home/ec2-user/deploy
#
#      # docker-compose 복사
#      - name: Copy docker-compose.yml
#        uses: appleboy/scp-action@master
#        with:
#          host: ${{ secrets.EC2_HOST }}
#          username: ec2-user
#          key: ${{ secrets.EC2_SSH_KEY }}
#          source: "docker-compose.yml"
#          target: "/home/ec2-user/deploy/"

      # Docker 이미지를 빌드합니다.
      - name: docker image build
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/github-actions-iamsouf .

      # Docker Hub에 로그인합니다. 로그인 정보는 GitHub Secrets를 통해 안전하게 관리됩니다.
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Docker Hub 사용자 이름
          password: ${{ secrets.DOCKER_PASSWORD }} # Docker Hub 비밀번호

      # 빌드된 Docker 이미지를 Docker Hub에 푸시합니다.
      - name: docker Hub push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/github-actions-iamsouf

  deploy:
    runs-on: ubuntu-latest
    needs: build-docker-image
    if: github.event_name == 'push'
    steps:
      # SSH를 사용하여 원격 서버에 배포
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TEST_SSH_HOST }}
          username: ${{ secrets.EC2_USER }}
          port: 22
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            
            cd ~/deploy
            
            docker image prune
            docker pull ${{ secrets.DOCKER_USERNAME }}/github-actions-iamsouf
            
            docker-compose -f docker-compose-test.yml --env-file ./souf.env down
            
            docker-compose -f docker-compose-test.yml --env-file ./souf.env up -d


